### ISSUE TITLE
return download URL

### ISSUE THREAD

**Issue by phrawzty** [cenk/putio.py#26]
Hello,

In this library, what is the canonical way to determine the download URL for a file? As in the cleanest, most correct method. 😄 

Context: I spent a bit of time poking at the (sorely out-dated) [Plex plugin for Put.io](https://github.com/logaritmisk/Put.io.bundle) which relies on the `putio.py` library. One of the missing pieces is a way to acquire the download URL for a given object without actually initiating the download - hence my query above.

Thank you!

**Comment by cenk** [comment]
Hello @phrawzty. Currently there is no way of getting the download URL with this library. This library works with OAuth2 and it needs to include oauth_token in URL to give access to the downloader. It is not safe to give it anywhere because it has full control over the account.

To give it safely, there is a need for a token that is more restricted to downloading of files only. Put.io has still not implemented OAuth2 scopes in order to do this. Sorry.
